export const dashboardMetrics = [
  {
    key: "heart",
    to: "/heart-rate",
    label: "Frequência cardíaca",
    subtitle: "Variação dos batimentos ao longo do dia",
    color: "--heart",
    value: 68,
    unit: "bpm",
    kind: "line",
  },
  {
    key: "sleep",
    to: "/sleep",
    label: "Sono",
    subtitle: "Duração, sono leve, profundo e REM",
    color: "--sleep",
    value: 76,
    unit: "Bom",
    kind: "gauge",
  },
  {
    key: "activity",
    to: "/workout",
    label: "Atividades",
    subtitle: "Passos, calorias e treinos",
    color: "--activity",
    value: 96,
    unit: "Excelente",
    kind: "gauge",
  },
  {
    key: "recovery",
    to: "/recovery",
    label: "Recuperação e estresse",
    subtitle: "Conheça seu ritmo e sua recuperação",
    color: "--cycle",
    value: 78,
    unit: "Recuperação",
    kind: "gauge",
  },
  {
    key: "sport",
    to: "/progress",
    label: "Recordes pessoais",
    subtitle: "Sua evolução, no seu próprio ritmo",
    color: "--sport",
    value: 82,
    unit: "Progressão",
    kind: "gauge",
  },
  {
    key: "spo2",
    to: "/spo2",
    label: "Oxigênio no sangue",
    subtitle: "Saturação de oxigênio · SpO₂",
    color: "--oxygen",
    value: 98,
    unit: "%",
    kind: "bars",
  },
] as const;

export const demoSports = [
  {
    id: "run",
    icon: "directions_run",
    name: "Corrida",
    date: "Hoje, 07:30",
    value: "5,2",
    unit: "km",
    duration: "32:45",
  },
  {
    id: "bike",
    icon: "directions_bike",
    name: "Ciclismo",
    date: "Ontem, 18:15",
    value: "15,8",
    unit: "km",
    duration: "45:12",
  },
  {
    id: "swim",
    icon: "pool",
    name: "Natação",
    date: "Exemplo de sessão",
    value: "1.200",
    unit: "m",
    duration: "32:05",
  },
  {
    id: "strength",
    icon: "fitness_center",
    name: "Força",
    date: "Exemplo de sessão",
    value: "12",
    unit: "séries",
    duration: "41:00",
  },
];

export const demoSleep = [
  { label: "Seg", deep: 1.5, light: 4.0, rem: 1.7 },
  { label: "Ter", deep: 1.2, light: 4.4, rem: 1.4 },
  { label: "Qua", deep: 1.8, light: 3.6, rem: 2.0 },
  { label: "Qui", deep: 1.6, light: 3.9, rem: 1.7 },
  { label: "Sex", deep: 1.4, light: 4.1, rem: 1.8 },
  { label: "Sáb", deep: 1.9, light: 4.2, rem: 1.9 },
  { label: "Dom", deep: 1.5, light: 3.5, rem: 1.6 },
];
export const demoMonthlySleep = [
  { label: "Sem 1", deep: 1.4, light: 3.8, rem: 1.6 },
  { label: "Sem 2", deep: 1.5, light: 3.9, rem: 1.8 },
  { label: "Sem 3", deep: 1.7, light: 4.0, rem: 1.9 },
  { label: "Sem 4", deep: 1.6, light: 3.9, rem: 1.7 },
];
